### ISSUE TITLE
print thoth.metrics-exporter.__version__ on startup

### ISSUE THREAD

**Issue by goern** [thoth-station/metrics-exporter#147]
just like user-api does: https://github.com/thoth-station/user-api/blob/master/thoth/user_api/entrypoint.py#L129

**Comment by bissenbay** [comment]
> just like user-api does: https://github.com/thoth-station/user-api/blob/master/thoth/user_api/entrypoint.py#L129

What about this https://github.com/thoth-station/metrics-exporter/blob/master/wsgi.py#L123?
