### ISSUE TITLE
Create a metric for number of CVEs stored in the Thoth's knowledge base

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#174]
As Thoth ops, I would like to see how many CVEs are we storing in the database. Let's expose a metric for that.

**Comment by goern** [comment]
As a Thoth User, I want to see what Python modules have cve, and which of my projects uses these modules, so that the cve could her fixed

**Comment by pacospace** [comment]
> As Thoth ops, I would like to see how many CVEs are we storing in the database. Let's expose a metric for that.

This metric already exists in the https://grafana.datahub.redhat.com/dashboard/db/thoth-knowledge-graph-content-metrics-test?refresh=1m&panelId=1&fullscreen&orgId=1 `total number of records for Main Tables', do you want to see it together with `python packages` https://grafana.datahub.redhat.com/dashboard/db/thoth-knowledge-graph-content-metrics-test?refresh=1m&panelId=23&fullscreen&orgId=1?

**Comment by pacospace** [comment]
> As a Thoth User, I want to see what Python modules have cve, and which of my projects uses these modules, so that the cve could her fixed

Could you please open a feature request in Open-API? :smiley:

**Comment by goern** [comment]
maybe its a feature for some kind ob background job?

**Comment by pacospace** [comment]
Something like `provenance-checker` but for checking if a Python package has any CVE (`CVE-checker`) and recommending which Python package to take care or providing already the new software stack working with that change? @fridex WDYT?

**Comment by fridex** [comment]
> Something like `provenance-checker` but for checking if a Python package has any CVE (`CVE-checker`) and recommending which Python package to take care or providing already the new software stack working with that change? @fridex WDYT?

Sounds like adviser to me :)

**Comment by goern** [comment]
Hmm ja, it is advisor for cve only, run as a job, righted by us, working on all repos known to Thoth... syn?

**Comment by fridex** [comment]
CC @pacospace do we have a metric for CVEs (how many CVEs are stored in the DB)?

> Hmm ja, it is advisor for cve only, run as a job, righted by us, working on all repos known to Thoth... syn?

It might be good to create this as part of some reports specific for packages, instead of running a job for this.

**Comment by pacospace** [comment]
kebechet administrator

> CC @pacospace do we have a metric for CVEs (how many CVEs are stored in the DB)?
> 

Not at the moment :) 

> > Hmm ja, it is advisor for cve only, run as a job, righted by us, working on all repos known to Thoth... syn?
> 
> It might be good to create this as part of some reports specific for packages, instead of running a job for this.

kebechet administrator is able to check when a new cve (kafka message) is create internally and check if any user which has kebechet manager active has that package,version,index in their softare stack with that CVE and in that case schedule kebechet run url

**Comment by fridex** [comment]
> > > Hmm ja, it is advisor for cve only, run as a job, righted by us, working on all repos known to Thoth... syn?
> > 
> > 
> > It might be good to create this as part of some reports specific for packages, instead of running a job for this.
> 
> Kebechet administrator is able to check when a new CVE (Kafka message) is created internally and check if any user, which has Kebechet active, has that package,version,index in their software stack with that CVE and in that case send message to schedule Kebechet run url.
> 
> By report what do you mean?

I was referring to this use case brought in the discussion:

> As a Thoth User, I want to see what Python modules have cve, and which of my projects uses these modules, so that the cve could her fixed

**Comment by pacospace** [comment]
> > > > Hmm ja, it is advisor for cve only, run as a job, righted by us, working on all repos known to Thoth... syn?
> > > 
> > > 
> > > It might be good to create this as part of some reports specific for packages, instead of running a job for this.
> > 
> > 
> > Kebechet administrator is able to check when a new CVE (Kafka message) is created internally and check if any user, which has Kebechet active, has that package,version,index in their software stack with that CVE and in that case send message to schedule Kebechet run url.
> > By report what do you mean?
> 
> I was referring to this use case brought in the discussion:
> 
> > As a Thoth User, I want to see what Python modules have cve, and which of my projects uses these modules, so that the cve could her fixed

similar to what we provide to check runs? but adding/showing also the filtered packages because of CVEs? https://github.com/thoth-station/management-api/pull/676/checks

**Comment by fridex** [comment]
Let's create metrics for CVEs, which was this issue originally, and let's talk about this at a meeting.

**Comment by pacospace** [comment]
> Let's create metrics for CVEs, which was this issue originally, and let's talk about this at a meeting.

sure! tech talk topic :)

**Comment by goern** [comment]
what is the state of this?! :)

**Comment by pacospace** [comment]
> what is the state of this?! :)

We can add it, sorry it fall back a bit :)

**Comment by pacospace** [comment]
- [ ] Extend query in database
- [ ] Add method to metrics-exporter
