### ISSUE TITLE
If schema is not up2date, metrics exporter might set all metrics to 0

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#181]
When the schema is not up2date and the metrics exporter fails to obtain metrics, the default metrics value is set always to 0. This causes issues and can be confusing when looking at metrics.

It would be better not to report metrics than reporting wrong metrics.

We could check schema in a liveness probe and kill unhealthy metrics-exporter not to produce wrong metrics.

**Comment by fridex** [comment]
CC @pacospace is this still relevant?

**Comment by pacospace** [comment]
> CC @pacospace is this still relevant?

I think it can consider this as second part with the new implementation coming. I'm exposing revisions by the components: https://github.com/thoth-station/metrics-exporter/issues/529

**Comment by pacospace** [comment]
> > CC @pacospace is this still relevant?
> 
> I think it can consider this as second part with the new implementation coming. I'm finishing exposing revisions by the components: #529. Even though in the discussion we had this behaviour is opposite: [#529 (comment)](https://github.com/thoth-station/metrics-exporter/issues/529#issuecomment-762687120)

Should we have?

- 1 match (component and database have same revision) 
- 0 no match (alarm required)
- 1 error (maybe metrics are not available) (this alarm should not be activated)

**Comment by fridex** [comment]
> > > CC @pacospace is this still relevant?
> > 
> > 
> > I think it can consider this as second part with the new implementation coming. I'm finishing exposing revisions by the components: #529. Even though in the discussion we had this behaviour is opposite: [#529 (comment)](https://github.com/thoth-station/metrics-exporter/issues/529#issuecomment-762687120)
> 
> Should we have
> 
> * 1 match (component and database have same revision)
> * 0 no match (alarm required)
> * -1 error (maybe metrics are not available) (this alarm should not be activated)

I think the issue we are trying to solve here is metrics-exporter schema being in sync with the database so we know all the queries on metrics-exporter give reasonable results.

This information can be deduced from https://github.com/thoth-station/metrics-exporter/issues/529 by checking alembic schema provided by thoth-storages and the alembic version present in the database. However, the semantics is slightly different. In #529 we are checking the match so that we know that "all the components in deployment have the right schema version". In case of this issue, the semantic is slightly different, that is "all the database metrics shown provide expected results". Users should not rely on metrics if the latter is not met as it can give an inaccurate overview on the data.

**Comment by pacospace** [comment]
> > > > CC @pacospace is this still relevant?
> > > 
> > > 
> > > I think it can consider this as second part with the new implementation coming. I'm finishing exposing revisions by the components: #529. Even though in the discussion we had this behaviour is opposite: [#529 (comment)](https://github.com/thoth-station/metrics-exporter/issues/529#issuecomment-762687120)
> > 
> > 
> > Should we have
> > 
> > * 1 match (component and database have same revision)
> > * 0 no match (alarm required)
> > * -1 error (maybe metrics are not available) (this alarm should not be activated)
> 
> I think the issue we are trying to solve here is metrics-exporter schema being in sync with the database so we know all the queries on metrics-exporter give reasonable results.

Right, then I think we can close this issues, as we do not have that metric anymore for metrics exporter.
> 
> This information can be deduced from #529 by checking alembic schema provided by thoth-storages and the alembic version present in the database. However, the semantics is slightly different. In #529 we are checking the match so that we know that "all the components in deployment have the right schema version". In case of this issue, the semantic is slightly different, that is "all the database metrics shown provide expected results". Users should not rely on metrics if the latter is not met as it can give an inaccurate overview on the data.

**Comment by goern** [comment]
@pacospace what is the state of this?

/label hacktoberfest

**Comment by goern** [comment]
@pacospace what is the state of this?

**Comment by pacospace** [comment]
> @pacospace what is the state of this?

We still need to implement this! I will have a look
