### ISSUE TITLE
deploy to stage

### ISSUE THREAD

**Issue by goern** [thoth-station/metrics-exporter#195]
**Short Summary**
Deploy the latest fixes.

**Workitem List**

- [x] new upstream release: thoth-storages, https://github.com/thoth-station/storages/issues/1282
- [x] build paas.psi.redhat.com:thoth-test-core:buildconfig/metrics-exporter
- [x] push to quay as v0.6.0-dev
- [x] import image to thoth-infra-stage
- [x] deploy paas.psi.redhat.com:thoth-frontend-stage:deploymentconfig/metrics-exporter

**Additional context**
n/a

**Comment by fridex** [comment]
Already done.
