### ISSUE TITLE
RFE: Do not maintain a list of workload/job types explicitly

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#271]
Based on #270 

Not to maintain the listing explicitly and not introduce a need to adjust metrics-exporter each time we add a new job/workload, we can ask for `operator=workload` label and count `component=*` labels. The same for `operator=graph-sync` and `graph-sync-type=*`. This way, each time we add a new job/workload type the metrics get automatically adjusted.

As we soon move to argo workflows which will require changes in metrics-exporter as well, I'm leaving this as an RFE.

**Comment by pacospace** [comment]
I think we can close this as we do not maintain any list of workfload, wdyt @fridex ?

**Comment by fridex** [comment]
Yes, we can close this :+1:
