### ISSUE TITLE
kebechet info

### ISSUE THREAD

**Issue by goern** [thoth-station/metrics-exporter#404]

**Comment by pacospace** [comment]
I think @saisankargochhayat already took care of this: https://github.com/thoth-station/metrics-exporter/pull/395. Do you have more info that you want to see? They are shown in the dashboards as well

**Comment by saisankargochhayat** [comment]
@pacospace I think this was just used to run kebechet on this repo again.. or to send  a new webhook.

**Comment by pacospace** [comment]
> @pacospace I think this was just used to run kebechet on this repo again.. or to send a new webhook. We can close this maybe now..

hahaha my bad, it was in metrics-exporter and we were talking about SLI and info from components, so it was misleading for me :D
