### ISSUE TITLE
Check for corrupted database

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#408]
**Is your feature request related to a problem? Please describe.**

As Thoth ops, I would like to check if the database is in a healthy state.

**Describe the solution you'd like**

See https://github.com/thoth-station/storages/issues/1586#issuecomment-637714748

We can export a metric signalizing whether the database is corrupted. Also an alert can notify us about possible database issues.

**Additional context**

https://github.com/thoth-station/storages/issues/1586#issuecomment-637714748

**Comment by pacospace** [comment]
Reference:
- https://www.postgresql.org/docs/10/amcheck.html

**Comment by fridex** [comment]
The discussion has been moved to https://github.com/thoth-station/storages/issues/1885
