### ISSUE TITLE
Expose database schema for all the components as a metric

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#529]
**Is your feature request related to a problem? Please describe.**

I, as Thoth, would like to expose database schema info as a metric so that I can get alerted when components do not use the same schema.

**Describe the solution you'd like**

All the services - user-api, management-api, metrics-exporter expose metric about schema version so that people can be alerted if schema does not match.

**Comment by pacospace** [comment]
Thanks for opening this feature request. 

We currently check if those services have same thoth-storages version with latest release from PyPI.

But I understand this is not completely accurate as we cannot differentiate between releases that require a schema change or not. 

Task:

- [ ] create a method to check latest alembic version file available in a certain release

Expose metric about schema in the following components:

- [ ] metrics-exporter
- [ ] investigator
- [ ] user-api
- [ ] management-api

**Comment by pacospace** [comment]
The new solution should cover the following cases:

1. `thoth-storages` is released with new alembic migration.

In this case management-API need to have the latest `thoth-storages` in order to update the schema.

Therefore the check need to consider 
- storages version between pypi and management-API
- script alembic version vs database alembic version

The alarm will be creted when the new release has schema update required

2. `thoth-storages` is released without alembic migration

no alarm required (see case 1)

3. Any of the service using `thoth-storages` has version different from the database

Therefore the check need to consider
- script alembic version vs database alembic version

The alarm will be created when any of the service expose a script alembic version which is different from the database alembic version.

@harshad16 @goern @fridex

**Comment by fridex** [comment]
> The new solution should cover the following cases:
> 
> 1. `thoth-storages` is released with new alembic migration.
> 
> In this case management-API need to have the latest `thoth-storages` in order to update the schema.
> 
> Therefore the check need to consider
> 
> * storages version between pypi and management-API

This is not needed.

> * script alembic version vs database alembic version
> 
> The alarm will be creted when the new release has schema update required
> 
> 1. `thoth-storages` is released without alembic migration
> 
> no alarm required (see case 1)
> 
> 1. Any of the service using `thoth-storages` has version different from the database
> 
> Therefore the check need to consider
> 
> * script alembic version vs database alembic version
> 
> The alarm will be created when any of the service exposes a script alembic version which is different from the database alembic version, no matter which `thoth-storages` they have.
> 

The main purpose of this is to make sure all the components use the same database schema in one deployment (test/prod/...) and hence no possible issues when talking to the database can arise. This will be especially useful for multiple releases of Thoth and making sure we ship the right version of thoth-storages in all the components.

For this purpose, there is a need to refactor `is_schema_up2date`:

https://github.com/thoth-station/storages/blob/48258f503d69ecce3e61531e6bdbc35f450640ed/thoth/storages/graph/postgres.py#L337-L338

create two methods out of the method stated:

  * check the alembic schema present in source code files which is given by thoth-storages version installed
  * check the alembic schema present in the database

All the components can expose the alembic version string present in their thoth-storages code. One component (e.g. user-api) can expose a version of alembic present in the database as well. All this should be propagated to metrics. In that case, they will show:

* desired alembic version which is present in the database (e.g. exposed by user api)
* alembic version in source code (thoth-storages) in all the components in a deployment
 
The latter should always match the desired alembic version (the first one); if not alert as possible issues can arise (some component is using wrong database schema, not matching the one present in the database).

**Comment by pacospace** [comment]
> > The new solution should cover the following cases:
> > 
> > 1. `thoth-storages` is released with new alembic migration.
> > 
> > In this case management-API need to have the latest `thoth-storages` in order to update the schema.
> > Therefore the check need to consider
> > 
> > * storages version between pypi and management-API
> 
> This is not needed.
> 
> > * script alembic version vs database alembic version
> > 
> > The alarm will be creted when the new release has schema update required
> > 
> > 1. `thoth-storages` is released without alembic migration
> > 
> > no alarm required (see case 1)
> > 
> > 1. Any of the service using `thoth-storages` has version different from the database
> > 
> > Therefore the check need to consider
> > 
> > * script alembic version vs database alembic version
> > 
> > The alarm will be created when any of the service exposes a script alembic version which is different from the database alembic version, no matter which `thoth-storages` they have.
> 
> The main purpose of this is to make sure all the components use the same database schema in one deployment (test/prod/...) and hence no possible issues when talking to the database can arise. This will be especially useful for multiple releases of Thoth and making sure we ship the right version of thoth-storages in all the components.
> 
> For this purpose, there is a need to refactor `is_schema_up2date`:
> 
> https://github.com/thoth-station/storages/blob/48258f503d69ecce3e61531e6bdbc35f450640ed/thoth/storages/graph/postgres.py#L337-L338
> 
> create two methods out of the method stated:
> 
> * check the alembic schema present in source code files which is given by thoth-storages version installed
> * check the alembic schema present in the database
> 
> All the components can expose the alembic version string present in their thoth-storages code. One component (e.g. metrics-exporter) can expose a version of alembic present in the database as well. All this should be propagated to metrics. In that case, they will show:
> 
> * desired alembic version which is present in the database (e.g. exposed by metrics-exporter)
> * alembic version in source code (thoth-storages) in all the components in a deployment
> 
> The latter should always match the desired alembic version (the first one); if not alert as possible issues can arise (some component is using wrong database schema, not matching the one present in the database).

Thanks then only the new methods will be created and I ll remove old logic to match versions.

**Comment by pacospace** [comment]
> > The new solution should cover the following cases:
> > 
> > 1. `thoth-storages` is released with new alembic migration.
> > 
> > In this case management-API need to have the latest `thoth-storages` in order to update the schema.
> > Therefore the check need to consider
> > 
> > * storages version between pypi and management-API
> 
> This is not needed.
> 
> > * script alembic version vs database alembic version
> > 
> > The alarm will be creted when the new release has schema update required
> > 
> > 1. `thoth-storages` is released without alembic migration
> > 
> > no alarm required (see case 1)
> > 
> > 1. Any of the service using `thoth-storages` has version different from the database
> > 
> > Therefore the check need to consider
> > 
> > * script alembic version vs database alembic version
> > 
> > The alarm will be created when any of the service exposes a script alembic version which is different from the database alembic version, no matter which `thoth-storages` they have.
> 
> The main purpose of this is to make sure all the components use the same database schema in one deployment (test/prod/...) and hence no possible issues when talking to the database can arise. This will be especially useful for multiple releases of Thoth and making sure we ship the right version of thoth-storages in all the components.
> 
> For this purpose, there is a need to refactor `is_schema_up2date`:
> 
> https://github.com/thoth-station/storages/blob/48258f503d69ecce3e61531e6bdbc35f450640ed/thoth/storages/graph/postgres.py#L337-L338
> 
> create two methods out of the method stated:
> 
> * check the alembic schema present in source code files which is given by thoth-storages version installed
> * check the alembic schema present in the database
> 
> All the components can expose the alembic version string present in their thoth-storages code. One component (e.g. metrics-exporter) can expose a version of alembic present in the database as well. All this should be propagated to metrics. In that case, they will show:
> 
> * desired alembic version which is present in the database (e.g. exposed by metrics-exporter)
> * alembic version in source code (thoth-storages) in all the components in a deployment
> 
> The latter should always match the desired alembic version (the first one); if not alert as possible issues can arise (some component is using wrong database schema, not matching the one present in the database).

I think management-API should be the one exposing the database version because it is the only component that can update the database schema. 

example:
`thoth_{component}_table_head_version(revision=f"{revision}") = 1`

`thoth_{component}_script_head_version(revision=f"{revision}") = 1`

- 1 to show the current revision up
- 0 otherwise

Then the other components will only push metric with version head from scripts

Finally, in metrics exporter, we will check matches and expose:

- 1 no match (alarm required)
- 0 match
- -1 error (maybe metrics are not available) (this alarm should not be activated)

for example `thoth_component_schema_check(component=f"{component}")`

then we can set alarms for each component with value set to 1.

**Comment by fridex** [comment]
> > > The new solution should cover the following cases:
> > > 
> > > 1. `thoth-storages` is released with new alembic migration.
> > > 
> > > In this case management-API need to have the latest `thoth-storages` in order to update the schema.
> > > Therefore the check need to consider
> > > 
> > > * storages version between pypi and management-API
> > 
> > 
> > This is not needed.
> > > * script alembic version vs database alembic version
> > > 
> > > The alarm will be creted when the new release has schema update required
> > > 
> > > 1. `thoth-storages` is released without alembic migration
> > > 
> > > no alarm required (see case 1)
> > > 
> > > 1. Any of the service using `thoth-storages` has version different from the database
> > > 
> > > Therefore the check need to consider
> > > 
> > > * script alembic version vs database alembic version
> > > 
> > > The alarm will be created when any of the service exposes a script alembic version which is different from the database alembic version, no matter which `thoth-storages` they have.
> > 
> > 
> > The main purpose of this is to make sure all the components use the same database schema in one deployment (test/prod/...) and hence no possible issues when talking to the database can arise. This will be especially useful for multiple releases of Thoth and making sure we ship the right version of thoth-storages in all the components.
> > For this purpose, there is a need to refactor `is_schema_up2date`:
> > https://github.com/thoth-station/storages/blob/48258f503d69ecce3e61531e6bdbc35f450640ed/thoth/storages/graph/postgres.py#L337-L338
> > create two methods out of the method stated:
> > 
> > * check the alembic schema present in source code files which is given by thoth-storages version installed
> > * check the alembic schema present in the database
> > 
> > All the components can expose the alembic version string present in their thoth-storages code. One component (e.g. metrics-exporter) can expose a version of alembic present in the database as well. All this should be propagated to metrics. In that case, they will show:
> > 
> > * desired alembic version which is present in the database (e.g. exposed by metrics-exporter)
> > * alembic version in source code (thoth-storages) in all the components in a deployment
> > 
> > The latter should always match the desired alembic version (the first one); if not alert as possible issues can arise (some component is using wrong database schema, not matching the one present in the database).
> 
> I think management-API should be the one exposing the database version because it is the only component that can update the database schema.

I would not use management API for this purpose. The result of the database schema query is a deployment metric and hence the most suitable component for this is metrics-exporter to me - it is not related to management API component metrics.

> example:
> `thoth_{component}_table_head_version(revision=f"{revision}") = 1`
> 
> `thoth_{component}_script_head_version(revision=f"{revision}") = 1`
> 
> * 1 to show the current revision up
> * 0 otherwise
> 
> Then the other components will only push metric with version head from scripts
> 
> Finally, in metrics exporter, we will check matches and expose:
> 
> * 1 no match (alarm required)
> * 0 match
> * -1 error (maybe metrics are not available) (this alarm should not be activated)
> 
> for example `thoth_component_schema_check(component=f"{component}")`
> 
> then we can set alarms for each component with value set to 1.
> 
> In this way we can also see from grafana what alembic version head from script, togheter with all library versions: https://grafana.datahub.redhat.com/dashboard/db/thoth-service-metrics?refresh=30s&orgId=1
> 
> @fridex wdyt?

+1
