### ISSUE TITLE
Expose users number per active Kebechet managers

### ISSUE THREAD

**Issue by pacospace** [thoth-station/metrics-exporter#559]
Is your feature request related to a problem? Please describe.

As discussed on the chat with @fridex , we could extend metrics so that we expose also information about users number per active Kebechet managers.

Describe the solution you'd like
Introduce a metric that would compute number of unique users per Kebechet manager (`source_type==KEBECHET`).

**Comment by pacospace** [comment]
this can be obtained once https://github.com/thoth-station/storages/pull/2293/files is active

**Comment by xtuchyna** [comment]
What is meant under users active per kebechet managers?

Is that related to only people who use Kebechet within repo? Or is it specific for anybody who used kebechet (so that the data of kebechet usage is collected within repository w.r.t. to the contributor's name?

**Comment by pacospace** [comment]
> What is meant under users active per kebechet managers?
> 
> Is that related to only people who use Kebechet within repo? Or is it specific for anybody who used kebechet (so that the data of kebechet usage is collected within repository w.r.t. to the contributor's name?

we already know one many users have kebechet active, and we want to know how many users have specific managers active, which is an information we store in the database, so queries can be created to check from there.

**Comment by goern** [comment]
what is the state of this one?

**Comment by pacospace** [comment]
> what is the state of this one?

It needs to be implemented:

- [ ] Add queries to storages
- [ ] Expose metrics in metrics-exporter

**Comment by goern** [comment]
@xtuchyna @pacospace please put some energy into this :exploding_head: thx

**Comment by pacospace** [comment]
> @xtuchyna @pacospace please put some energy into this  thx

Queries are created, but someone needs to review them :) and then we just need to add them here, I ll ping someone for the review :)

**Comment by pacospace** [comment]
> > @xtuchyna @pacospace please put some energy into this  thx
> 
> Queries are created, but someone needs to review them :) and then we just need to add them here, I ll ping someone for the review :) sorry for delay

Just a small comment, we won't see any users, untile we have Kebechet external trigger in place :)

**Comment by pacospace** [comment]
@xtuchyna do you add the new metrics? queries in thoth-storages already exist and the new thoth-storages version is available in metrics-exporter.

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/kebechet/issues/679
