### ISSUE TITLE
Create a metric which exposes number of rows in alembic version table

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#573]
**Is your feature request related to a problem? Please describe.**

To prevent issues like the one reported in https://github.com/thoth-station/storages/issues/2169 we should expose a metric which shows number of rows in the alembic version table. If number of rows is not equal to 1, we should alert.

**Describe the solution you'd like**

- [x] introduce a query in thoth-storages that counts the number of rows in the alembic version table
- [x] expose metric in metrics-exporter which shows the number of alembic rows
- [ ] setup alert which is sent when number of rows in the alembic version table is not equal to 1

**Comment by pacospace** [comment]
alarm added in https://github.com/thoth-station/thoth-application/issues/854, the metric is already exposed in new metrics-exporter
