### ISSUE TITLE
Add metrics related to build-analysis

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#581]
**Is your feature request related to a problem? Please describe.**

As we introduced build-analysis, let's expose metrics that would give us insights into the aggregated data and workflows.

**Describe the solution you'd like**

- [ ] introduce metrics related to build-analysis Argo workflows (running, ...)
- [ ] ...

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> As we introduced build-analysis, let's expose metrics that would give us insights into the aggregated data and workflows.
> 
> **Describe the solution you'd like**
> 
> * [ ]  introduce metrics related to build-analysis Argo workflows (running, ...)

Can you please point the argo workflows tamplates for that specific compoent? I cannot find in thoth-application build-analysis components.
> * [ ]  introduce metrics related to documents stored on Ceph (number of stored prepared buildlog-parser results) using thoth-storages adapter
We removed the monitor on number of report stored on Ceph because the query take too much time for metrics-exporter to work correctly when too many reports are stored on Ceph.

> * [ ]  ...

**Comment by fridex** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > As we introduced build-analysis, let's expose metrics that would give us insights into the aggregated data and workflows.
> > **Describe the solution you'd like**
> > 
> > * [ ]   introduce metrics related to build-analysis Argo workflows (running, ...)
> 
> Can you please point the argo workflows tamplates for that specific compoent? I cannot find in thoth-application build-analysis component.

It should be present in https://github.com/thoth-station/thoth-application/blob/master/package-extract/base/openshift-templates/build-analysis.yaml

**Comment by pacospace** [comment]
> > > **Is your feature request related to a problem? Please describe.**
> > > As we introduced build-analysis, let's expose metrics that would give us insights into the aggregated data and workflows.
> > > **Describe the solution you'd like**
> > > 
> > > * [ ]    introduce metrics related to build-analysis Argo workflows (running, ...)
> > 
> > 
> > Can you please point the argo workflows tamplates for that specific compoent? I cannot find in thoth-application build-analysis component.
> 
> It should be present in https://github.com/thoth-station/thoth-application/blob/master/package-extract/base/openshift-templates/build-analysis.yaml

Thanks!! Sorry I was confused by the name :) 
We can use argo workflows metrics directly then, I ll send a PR for that to be consistent with the other components and we can receive these metrics in the email every friday.
