### ISSUE TITLE
Create an alert if solvers in configmap do not match the ones in the database

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#586]
**Is your feature request related to a problem? Please describe.**

Following discussion in https://github.com/thoth-station/storages/pull/2197 we should have an alert when 

**Describe the solution you'd like**

Expose information about solvers in configmap and solvers available in the database. If they do not match, create an alert as the deployment is not configured properly.

**Comment by pacospace** [comment]
This was created and present in current metrics-exporter, alarm to be created is in the list: https://github.com/thoth-station/thoth-application/issues/854
