### ISSUE TITLE
Create an alert when solvers do not match Thoth s2i offered

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#598]
**Is your feature request related to a problem? Please describe.**

See procedure described in https://github.com/thoth-station/thoth-application/pull/849. Basically, we should expose metrics about the number of registered solvers and number of Thoth s2i the system analyzed. If these two do not match:

* if number of solvers > number of Thoth s2i analyzed - we do not have Thoth s2i registered in the system for which we could do recommendations for
* if number of solvers < number of Thoth s2i analyzed - we do not have solvers installed for Thoth s2i environments we offer

**Describe the solution you'd like**

Create metrics for the number of solvers registered and the number of Thoth s2i available to users. If these two do not match that means the system keeps too much information that cannot be used or some information is missing.

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/854

**Comment by pacospace** [comment]
- [ ] create missing metrics in metrics-exporter
