### ISSUE TITLE
Expose information about message versions seen in a deployment

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#611]
**Is your feature request related to a problem? Please describe.**

I, as Thoth operator, would like to see what message versions are sent in a deployment. For this purpose, we can create a consumer that does not acknowledge messages, but rather marks down what versions were seen in a deployment (per topic) as suggested by @KPostOffice.

**Describe the solution you'd like**

Have a metric exposing versions of messages that are seen in a deployment.

**Additional context**

This way we can see what message versions are used in a deployment.

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/investigator/pull/467

**Comment by KPostOffice** [comment]
TODO: create deployment/service/route which runs in `message_metrics` mode

**Comment by pacospace** [comment]
I think this can be close, I'll open another issue to have these metrics visualized in a dashboard.
