### ISSUE TITLE
Export metrics related to ingestion in percentage

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#619]
**Is your feature request related to a problem? Please describe.**

I, as Thoth operator, would like to know the current state of the data ingestion. It is possible to do so using the current set of metrics, but it looks not that intuitive to me.

**Describe the solution you'd like**

Show the state of ingestion as a percentage (% to complete ingestion based on the current state):

- [ ] show % of known python releases in comparison to PyPI - this could be read as "Thoth knowns N% of PyPI". This can be calculated with respect to releases known by Thoth and releases available on PyPI
- [ ] show % of solved python releases by a solver in comparison to releases registered to Thoth - this could be read as "Thoth's solver X solved N% of releases known to Thoth" (progress of a solver)
- [ ] show % of analyzed python releases by security indicators in comparison to releases registered to Thoth - this could be read as "Thoth's security analysis analyzed N% of releases known to Thoth" (progress of security analysis)

**Describe alternatives you've considered**

Keep metrics as are.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I, as Thoth operator, would like to know the current state of the data ingestion. It is possible to do so using the current set of metrics, but it looks not that intuitive to me.
> 
> **Describe the solution you'd like**
> 
> Show the state of ingestion as a percentage (% to complete ingestion based on the current state):
> 
> * [ ]  show % of known python releases in comparison to PyPI - this could be read as "Thoth knowns N% of PyPI". This can be calculated with respect to releases known by Thoth and releases available on PyPI
> * [ ]  show % of solved python releases by a solver in comparison to releases registered to Thoth - this could be read as "Thoth's solver X solved N% of releases known to Thoth" (progress of a solver)

![Screenshot from 2021-03-03 17-45-20](https://user-images.githubusercontent.com/27498679/109840374-5924b700-7c48-11eb-9756-eb3a5fccba98.png)

> * [ ]  show % of analyzed python releases by security indicators in comparison to releases registered to Thoth - this could be read as "Thoth's security analysis analyzed N% of releases known to Thoth" (progress of security analysis)

![Screenshot from 2021-03-03 17-48-25](https://user-images.githubusercontent.com/27498679/109840798-bd477b00-7c48-11eb-8727-47bcc526e2b6.png)

> 
> **Describe alternatives you've considered**
> 
> Keep metrics as are.

WDYT @fridex ?

**Comment by fridex** [comment]
LGTM! :100: 

Can be the same accomplished for security analyzers?

**Comment by fridex** [comment]
OK, now I see the green box :+1: Looks good :+1:

**Comment by pacospace** [comment]
> OK, now I see the green box  Looks good

This is currently in stage environment. I will update the grafana dashboard json in thoth-application for prod and then we need to wait for https://github.com/thoth-station/thoth-application/issues/1004#issuecomment-789873143 to have this there 💯

**Comment by fridex** [comment]
Awesome :+1:
