### ISSUE TITLE
Estimate number of days needed to support a new runtime environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#723]
**Is your feature request related to a problem? Please describe.**

As Thoth user/operator/PM, I would like to know how many days are required to support the new runtime environment given the allocated resources for deployment and number of packages Thoth already ingested for other environments.

In other words: 

> if I plug a new solver now, how many days is estimated to solve all the packages in the database?

**Describe the solution you'd like**

Have a metric that shows this information on Grafana dashboards.

**Comment by pacospace** [comment]
- [x] add metric
- [ ] move stage dashboard to prod

**Comment by pacospace** [comment]
> * [x]  add metric (number of package releases in thoth / learning rate)

Example from stage: 
![Screenshot from 2021-06-28 10-00-08](https://user-images.githubusercontent.com/27498679/123601289-cb249b80-d7f7-11eb-8228-a3a4dd6bd918.png)

Source: https://grafana.datahub.redhat.com/dashboard/db/thoth-sli-slo?refresh=30s&orgId=1

> * [ ]  move stage dashboard to prod

**Comment by pacospace** [comment]
Already in prod https://github.com/thoth-station/thoth-application/pull/1800
