### ISSUE TITLE
Number of unsolved packages suddenly increased in stage environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#771]
**Describe the bug**

After migration done in https://github.com/thoth-station/thoth-application/issues/1975, the number of unsolved packages increased to more than 1M:

![Screenshot_2021-09-20_14-50-37](https://user-images.githubusercontent.com/880687/134005150-7fefeeaf-7522-4466-acd7-9af21e25bad8.png)

**To Reproduce**
1. Go to the stage environment
2. Check metrics exposed
3. See the number of unsolved packages

**Expected behavior**

The increase looks suspicious and is worth investigating. Not sure if it is an issue on metrics-exporter side though.

**Comment by pacospace** [comment]
It seems removing the join of PythonPackageIndex created that issue. See: https://github.com/thoth-station/storages/pull/2401/files, I'm going to revert those changes
